### ISSUE TITLE
bin/console debug:event-dispatcher is not working

### ISSUE THREAD

**Issue by bartdens** [exesser/exess-skeleton#36] opened 2021-06-18 09:49 UTC
**Version(s) affected**: all

**Description**  

This command os not working, it outputs:

`[ERROR] Event dispatcher "event_dispatcher" is not available.`

**Steps to reproduce**  

bin/console debug:event-dispatcher

**Comment by kristofvc** [comment] 2021-06-18 10:09
Indeed we don't use the regular symfony event_dispatcher yet but the custom one we implemented to use with slim. I suspect we need to do some refactoring for this

**Comment by kristofvc** [comment] 2021-06-18 10:15
@devartbvba Cannot reproduce, might be a wrongly cached container in your case?

**Comment by kristofvc** [comment] 2021-06-18 11:18
Was accidentally fixed by updating composer and getting our versions in line!

**Closed as completed** 2021-06-18 11:18 UTC
Labels: bug, php
